### ISSUE TITLE
Tokens end up in corner given time

### ISSUE THREAD

**Issue by huskyskins** [theripper93/Patrol#9] opened 2021-06-18 20:13 UTC
I've been testing this out, and don't know why or how you would fix it, but all patrolling tokens end up working their way to a corner if given enough time.  I've walked away from a scene for a break, etc. and every time I return, any patrolling tokens are bouncing around in a corner.

Maybe, once they hit a wall or patrol perimeter, they don't choose that direction again for 3 or 4 recalculations?  That would at least get the tokens heading away far enough to give them a chance find a different wall to bounce off.

**Comment by yogiteck** [comment] 2021-07-15 14:36
Same for me. They end up in the bottom left corner, as if the random function was not as random as it should. I've tried many different area patterns thinking it could be the reason why but they always come back in that corner !

**Comment by yogiteck** [comment] 2021-07-15 14:57
I think I've found what the issue is. The random function is calculated this ways : 
Math.round(Math.random() * (validPositions.length - 1)). 

Let's say there are 4 valid positions (top, left, bottom, right). The random function gives a number between 0 and 1 (1 being excluded). It means the  function will give a number between 0 and 3 (3 being excluded). Then if we round that result, we have either 0, 1 or 2 with equal chances. BUT NOT 3 ! Could somebody confirm I'm right there ?

**Comment by theripper93** [comment] 2021-07-15 22:11
yes you are correct, i'll floor it and update it, i'll close the issue, let me know if it persists even with this edit

**Closed by theripper93** 2021-07-15 22:11 UTC
